//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonFiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public BonFiscal()
        //{
        //    this.BonProdus = new HashSet<BonProdus>();
        //}
        public BonFiscal(int IdCasier)
        {
            this.IdCasier = IdCasier;
            this.DataEliberare = System.DateTime.Now;
            SumaIncasata = 0;
        }
    
        public System.DateTime DataEliberare { get; set; }
        public int IdCasier { get; set; }
        public double SumaIncasata { get; set; }
        public int IdBon { get; set; }
    
        public virtual Utilizator Utilizator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonProdus> BonProdus { get; set; }
    }
}
