//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonProdus
    {
        public int IdBon { get; set; }
        public int IdProdus { get; set; }
        public int Cantitate { get; set; }
        public double Subtotal { get; set; }
    
        public virtual BonFiscal BonFiscal { get; set; }
    }
}
