//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BonProdus : INotifyPropertyChanged
    {
        private int _idBon;
        private int _idProdus;
        private int _cantitate;
        private double _subtotal;

        public int IdBon
        {
            get { return _idBon; }
            set
            {
                if (_idBon != value)
                {
                    _idBon = value;
                    OnPropertyChanged(nameof(IdBon));
                }
            }
        }

        public int IdProdus
        {
            get { return _idProdus; }
            set
            {
                if (_idProdus != value)
                {
                    _idProdus = value;
                    OnPropertyChanged(nameof(IdProdus));
                }
            }
        }

        public int Cantitate
        {
            get { return _cantitate; }
            set
            {
                if (_cantitate != value)
                {
                    _cantitate = value;
                    OnPropertyChanged(nameof(Cantitate));
                    OnPropertyChanged(nameof(Subtotal)); // Actualizează și Subtotal atunci când Cantitate se schimbă
                }
            }
        }

        public double Subtotal
        {
            get { return _subtotal; }
            set
            {
                if (_subtotal != value)
                {
                    _subtotal = value;
                    OnPropertyChanged(nameof(Subtotal));
                }
            }
        }
        public BonProdus(int idBon, int idProdus, int cantitate, double subtotal)
        {
            IdBon = idBon;
            IdProdus = idProdus;
            Cantitate = cantitate;
            Subtotal = subtotal;
        }
        public BonProdus(int idBon, int idProdus, double pret)
        {
            IdBon = idBon;
            IdProdus = idProdus;
            Cantitate = 1;
            Subtotal = pret;
        }

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public void IncrementCantitate()
        {
            Cantitate++;
        }
        public void AddSubtotal(int pret)
        {
            Subtotal += pret;
        }


        public virtual BonFiscal BonFiscal { get; set; }
    }
}
