//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public string MotivOferta { get; set; }
        public int IdProdus { get; set; }
        public int ProcentReducere { get; set; }
        public System.DateTime DataInceputOferta { get; set; }
        public System.DateTime DataFinalOferta { get; set; }
        public int IdOferta { get; set; }
    
        public virtual Produs Produs { get; set; }
    }
}
