//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produs
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produs(int id)
        {
            this.Oferta = new HashSet<Oferta>();
            this.StocProdus = new HashSet<StocProdus>();
        }

        public Produs(int id, string v, string categorie, int producator_Id, bool isActive) : this(id)
        {
            this.Id = id;
            this.Nume = v;
            Categorie = categorie;
            Producator_Id = producator_Id;
            IsActive = isActive;
        }

        public int Id { get; set; }
        public string Nume { get; set; }
        public string Categorie { get; set; }
        public int Producator_Id { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta> Oferta { get; set; }
        public virtual Producator Producator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StocProdus> StocProdus { get; set; }
    }
}
